// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: greptime/v1/health.proto

#include "greptime/v1/health.pb.h"
#include "greptime/v1/health.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace greptime {
namespace v1 {

static const char* HealthCheck_method_names[] = {
  "/greptime.v1.HealthCheck/HealthCheck",
};

std::unique_ptr< HealthCheck::Stub> HealthCheck::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HealthCheck::Stub> stub(new HealthCheck::Stub(channel, options));
  return stub;
}

HealthCheck::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_HealthCheck_(HealthCheck_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HealthCheck::Stub::HealthCheck(::grpc::ClientContext* context, const ::greptime::v1::HealthCheckRequest& request, ::greptime::v1::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::greptime::v1::HealthCheckRequest, ::greptime::v1::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void HealthCheck::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::greptime::v1::HealthCheckRequest* request, ::greptime::v1::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::greptime::v1::HealthCheckRequest, ::greptime::v1::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void HealthCheck::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::greptime::v1::HealthCheckRequest* request, ::greptime::v1::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::greptime::v1::HealthCheckResponse>* HealthCheck::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::greptime::v1::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::greptime::v1::HealthCheckResponse, ::greptime::v1::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::greptime::v1::HealthCheckResponse>* HealthCheck::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::greptime::v1::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

HealthCheck::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthCheck_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HealthCheck::Service, ::greptime::v1::HealthCheckRequest, ::greptime::v1::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HealthCheck::Service* service,
             ::grpc::ServerContext* ctx,
             const ::greptime::v1::HealthCheckRequest* req,
             ::greptime::v1::HealthCheckResponse* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
}

HealthCheck::Service::~Service() {
}

::grpc::Status HealthCheck::Service::HealthCheck(::grpc::ServerContext* context, const ::greptime::v1::HealthCheckRequest* request, ::greptime::v1::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace greptime
}  // namespace v1

