// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greptime/v1/meta/region.proto

package greptime.v1.meta;

public final class Region {
  private Region() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MigrateRegionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:greptime.v1.meta.MigrateRegionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
     * @return The header.
     */
    greptime.v1.meta.Common.RequestHeader getHeader();
    /**
     * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
     */
    greptime.v1.meta.Common.RequestHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>uint64 region_id = 3;</code>
     * @return The regionId.
     */
    long getRegionId();

    /**
     * <code>uint64 from_peer = 4;</code>
     * @return The fromPeer.
     */
    long getFromPeer();

    /**
     * <code>uint64 to_peer = 5;</code>
     * @return The toPeer.
     */
    long getToPeer();

    /**
     * <code>uint32 timeout_secs = 6;</code>
     * @return The timeoutSecs.
     */
    int getTimeoutSecs();

    /**
     * <pre>
     * Stable event metadata recorded with the submitted procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
     * @return Whether the eventContext field is set.
     */
    boolean hasEventContext();
    /**
     * <pre>
     * Stable event metadata recorded with the submitted procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
     * @return The eventContext.
     */
    greptime.v1.meta.Common.ProcedureEventContext getEventContext();
    /**
     * <pre>
     * Stable event metadata recorded with the submitted procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
     */
    greptime.v1.meta.Common.ProcedureEventContextOrBuilder getEventContextOrBuilder();

    /**
     * <pre>
     * Effective user that submitted the procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
     * @return Whether the actor field is set.
     */
    boolean hasActor();
    /**
     * <pre>
     * Effective user that submitted the procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
     * @return The actor.
     */
    greptime.v1.meta.Common.ProcedureActor getActor();
    /**
     * <pre>
     * Effective user that submitted the procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
     */
    greptime.v1.meta.Common.ProcedureActorOrBuilder getActorOrBuilder();
  }
  /**
   * Protobuf type {@code greptime.v1.meta.MigrateRegionRequest}
   */
  public static final class MigrateRegionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:greptime.v1.meta.MigrateRegionRequest)
      MigrateRegionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MigrateRegionRequest.newBuilder() to construct.
    private MigrateRegionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MigrateRegionRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MigrateRegionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MigrateRegionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              greptime.v1.meta.Common.RequestHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(greptime.v1.meta.Common.RequestHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              regionId_ = input.readUInt64();
              break;
            }
            case 32: {

              fromPeer_ = input.readUInt64();
              break;
            }
            case 40: {

              toPeer_ = input.readUInt64();
              break;
            }
            case 48: {

              timeoutSecs_ = input.readUInt32();
              break;
            }
            case 538: {
              greptime.v1.meta.Common.ProcedureEventContext.Builder subBuilder = null;
              if (eventContext_ != null) {
                subBuilder = eventContext_.toBuilder();
              }
              eventContext_ = input.readMessage(greptime.v1.meta.Common.ProcedureEventContext.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(eventContext_);
                eventContext_ = subBuilder.buildPartial();
              }

              break;
            }
            case 546: {
              greptime.v1.meta.Common.ProcedureActor.Builder subBuilder = null;
              if (actor_ != null) {
                subBuilder = actor_.toBuilder();
              }
              actor_ = input.readMessage(greptime.v1.meta.Common.ProcedureActor.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(actor_);
                actor_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              greptime.v1.meta.Region.MigrateRegionRequest.class, greptime.v1.meta.Region.MigrateRegionRequest.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private greptime.v1.meta.Common.RequestHeader header_;
    /**
     * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public greptime.v1.meta.Common.RequestHeader getHeader() {
      return header_ == null ? greptime.v1.meta.Common.RequestHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
     */
    @java.lang.Override
    public greptime.v1.meta.Common.RequestHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int REGION_ID_FIELD_NUMBER = 3;
    private long regionId_;
    /**
     * <code>uint64 region_id = 3;</code>
     * @return The regionId.
     */
    @java.lang.Override
    public long getRegionId() {
      return regionId_;
    }

    public static final int FROM_PEER_FIELD_NUMBER = 4;
    private long fromPeer_;
    /**
     * <code>uint64 from_peer = 4;</code>
     * @return The fromPeer.
     */
    @java.lang.Override
    public long getFromPeer() {
      return fromPeer_;
    }

    public static final int TO_PEER_FIELD_NUMBER = 5;
    private long toPeer_;
    /**
     * <code>uint64 to_peer = 5;</code>
     * @return The toPeer.
     */
    @java.lang.Override
    public long getToPeer() {
      return toPeer_;
    }

    public static final int TIMEOUT_SECS_FIELD_NUMBER = 6;
    private int timeoutSecs_;
    /**
     * <code>uint32 timeout_secs = 6;</code>
     * @return The timeoutSecs.
     */
    @java.lang.Override
    public int getTimeoutSecs() {
      return timeoutSecs_;
    }

    public static final int EVENT_CONTEXT_FIELD_NUMBER = 67;
    private greptime.v1.meta.Common.ProcedureEventContext eventContext_;
    /**
     * <pre>
     * Stable event metadata recorded with the submitted procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
     * @return Whether the eventContext field is set.
     */
    @java.lang.Override
    public boolean hasEventContext() {
      return eventContext_ != null;
    }
    /**
     * <pre>
     * Stable event metadata recorded with the submitted procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
     * @return The eventContext.
     */
    @java.lang.Override
    public greptime.v1.meta.Common.ProcedureEventContext getEventContext() {
      return eventContext_ == null ? greptime.v1.meta.Common.ProcedureEventContext.getDefaultInstance() : eventContext_;
    }
    /**
     * <pre>
     * Stable event metadata recorded with the submitted procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
     */
    @java.lang.Override
    public greptime.v1.meta.Common.ProcedureEventContextOrBuilder getEventContextOrBuilder() {
      return getEventContext();
    }

    public static final int ACTOR_FIELD_NUMBER = 68;
    private greptime.v1.meta.Common.ProcedureActor actor_;
    /**
     * <pre>
     * Effective user that submitted the procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
     * @return Whether the actor field is set.
     */
    @java.lang.Override
    public boolean hasActor() {
      return actor_ != null;
    }
    /**
     * <pre>
     * Effective user that submitted the procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
     * @return The actor.
     */
    @java.lang.Override
    public greptime.v1.meta.Common.ProcedureActor getActor() {
      return actor_ == null ? greptime.v1.meta.Common.ProcedureActor.getDefaultInstance() : actor_;
    }
    /**
     * <pre>
     * Effective user that submitted the procedure.
     * </pre>
     *
     * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
     */
    @java.lang.Override
    public greptime.v1.meta.Common.ProcedureActorOrBuilder getActorOrBuilder() {
      return getActor();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (regionId_ != 0L) {
        output.writeUInt64(3, regionId_);
      }
      if (fromPeer_ != 0L) {
        output.writeUInt64(4, fromPeer_);
      }
      if (toPeer_ != 0L) {
        output.writeUInt64(5, toPeer_);
      }
      if (timeoutSecs_ != 0) {
        output.writeUInt32(6, timeoutSecs_);
      }
      if (eventContext_ != null) {
        output.writeMessage(67, getEventContext());
      }
      if (actor_ != null) {
        output.writeMessage(68, getActor());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (regionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, regionId_);
      }
      if (fromPeer_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, fromPeer_);
      }
      if (toPeer_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, toPeer_);
      }
      if (timeoutSecs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, timeoutSecs_);
      }
      if (eventContext_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(67, getEventContext());
      }
      if (actor_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(68, getActor());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof greptime.v1.meta.Region.MigrateRegionRequest)) {
        return super.equals(obj);
      }
      greptime.v1.meta.Region.MigrateRegionRequest other = (greptime.v1.meta.Region.MigrateRegionRequest) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (getRegionId()
          != other.getRegionId()) return false;
      if (getFromPeer()
          != other.getFromPeer()) return false;
      if (getToPeer()
          != other.getToPeer()) return false;
      if (getTimeoutSecs()
          != other.getTimeoutSecs()) return false;
      if (hasEventContext() != other.hasEventContext()) return false;
      if (hasEventContext()) {
        if (!getEventContext()
            .equals(other.getEventContext())) return false;
      }
      if (hasActor() != other.hasActor()) return false;
      if (hasActor()) {
        if (!getActor()
            .equals(other.getActor())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + REGION_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRegionId());
      hash = (37 * hash) + FROM_PEER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromPeer());
      hash = (37 * hash) + TO_PEER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToPeer());
      hash = (37 * hash) + TIMEOUT_SECS_FIELD_NUMBER;
      hash = (53 * hash) + getTimeoutSecs();
      if (hasEventContext()) {
        hash = (37 * hash) + EVENT_CONTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getEventContext().hashCode();
      }
      if (hasActor()) {
        hash = (37 * hash) + ACTOR_FIELD_NUMBER;
        hash = (53 * hash) + getActor().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static greptime.v1.meta.Region.MigrateRegionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(greptime.v1.meta.Region.MigrateRegionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code greptime.v1.meta.MigrateRegionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:greptime.v1.meta.MigrateRegionRequest)
        greptime.v1.meta.Region.MigrateRegionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                greptime.v1.meta.Region.MigrateRegionRequest.class, greptime.v1.meta.Region.MigrateRegionRequest.Builder.class);
      }

      // Construct using greptime.v1.meta.Region.MigrateRegionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        regionId_ = 0L;

        fromPeer_ = 0L;

        toPeer_ = 0L;

        timeoutSecs_ = 0;

        if (eventContextBuilder_ == null) {
          eventContext_ = null;
        } else {
          eventContext_ = null;
          eventContextBuilder_ = null;
        }
        if (actorBuilder_ == null) {
          actor_ = null;
        } else {
          actor_ = null;
          actorBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionRequest_descriptor;
      }

      @java.lang.Override
      public greptime.v1.meta.Region.MigrateRegionRequest getDefaultInstanceForType() {
        return greptime.v1.meta.Region.MigrateRegionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public greptime.v1.meta.Region.MigrateRegionRequest build() {
        greptime.v1.meta.Region.MigrateRegionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public greptime.v1.meta.Region.MigrateRegionRequest buildPartial() {
        greptime.v1.meta.Region.MigrateRegionRequest result = new greptime.v1.meta.Region.MigrateRegionRequest(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.regionId_ = regionId_;
        result.fromPeer_ = fromPeer_;
        result.toPeer_ = toPeer_;
        result.timeoutSecs_ = timeoutSecs_;
        if (eventContextBuilder_ == null) {
          result.eventContext_ = eventContext_;
        } else {
          result.eventContext_ = eventContextBuilder_.build();
        }
        if (actorBuilder_ == null) {
          result.actor_ = actor_;
        } else {
          result.actor_ = actorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof greptime.v1.meta.Region.MigrateRegionRequest) {
          return mergeFrom((greptime.v1.meta.Region.MigrateRegionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(greptime.v1.meta.Region.MigrateRegionRequest other) {
        if (other == greptime.v1.meta.Region.MigrateRegionRequest.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getRegionId() != 0L) {
          setRegionId(other.getRegionId());
        }
        if (other.getFromPeer() != 0L) {
          setFromPeer(other.getFromPeer());
        }
        if (other.getToPeer() != 0L) {
          setToPeer(other.getToPeer());
        }
        if (other.getTimeoutSecs() != 0) {
          setTimeoutSecs(other.getTimeoutSecs());
        }
        if (other.hasEventContext()) {
          mergeEventContext(other.getEventContext());
        }
        if (other.hasActor()) {
          mergeActor(other.getActor());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        greptime.v1.meta.Region.MigrateRegionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (greptime.v1.meta.Region.MigrateRegionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private greptime.v1.meta.Common.RequestHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.RequestHeader, greptime.v1.meta.Common.RequestHeader.Builder, greptime.v1.meta.Common.RequestHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       * @return The header.
       */
      public greptime.v1.meta.Common.RequestHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? greptime.v1.meta.Common.RequestHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       */
      public Builder setHeader(greptime.v1.meta.Common.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       */
      public Builder setHeader(
          greptime.v1.meta.Common.RequestHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       */
      public Builder mergeHeader(greptime.v1.meta.Common.RequestHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              greptime.v1.meta.Common.RequestHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       */
      public greptime.v1.meta.Common.RequestHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       */
      public greptime.v1.meta.Common.RequestHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              greptime.v1.meta.Common.RequestHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.greptime.v1.meta.RequestHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.RequestHeader, greptime.v1.meta.Common.RequestHeader.Builder, greptime.v1.meta.Common.RequestHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              greptime.v1.meta.Common.RequestHeader, greptime.v1.meta.Common.RequestHeader.Builder, greptime.v1.meta.Common.RequestHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private long regionId_ ;
      /**
       * <code>uint64 region_id = 3;</code>
       * @return The regionId.
       */
      @java.lang.Override
      public long getRegionId() {
        return regionId_;
      }
      /**
       * <code>uint64 region_id = 3;</code>
       * @param value The regionId to set.
       * @return This builder for chaining.
       */
      public Builder setRegionId(long value) {
        
        regionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 region_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegionId() {
        
        regionId_ = 0L;
        onChanged();
        return this;
      }

      private long fromPeer_ ;
      /**
       * <code>uint64 from_peer = 4;</code>
       * @return The fromPeer.
       */
      @java.lang.Override
      public long getFromPeer() {
        return fromPeer_;
      }
      /**
       * <code>uint64 from_peer = 4;</code>
       * @param value The fromPeer to set.
       * @return This builder for chaining.
       */
      public Builder setFromPeer(long value) {
        
        fromPeer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 from_peer = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromPeer() {
        
        fromPeer_ = 0L;
        onChanged();
        return this;
      }

      private long toPeer_ ;
      /**
       * <code>uint64 to_peer = 5;</code>
       * @return The toPeer.
       */
      @java.lang.Override
      public long getToPeer() {
        return toPeer_;
      }
      /**
       * <code>uint64 to_peer = 5;</code>
       * @param value The toPeer to set.
       * @return This builder for chaining.
       */
      public Builder setToPeer(long value) {
        
        toPeer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 to_peer = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearToPeer() {
        
        toPeer_ = 0L;
        onChanged();
        return this;
      }

      private int timeoutSecs_ ;
      /**
       * <code>uint32 timeout_secs = 6;</code>
       * @return The timeoutSecs.
       */
      @java.lang.Override
      public int getTimeoutSecs() {
        return timeoutSecs_;
      }
      /**
       * <code>uint32 timeout_secs = 6;</code>
       * @param value The timeoutSecs to set.
       * @return This builder for chaining.
       */
      public Builder setTimeoutSecs(int value) {
        
        timeoutSecs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 timeout_secs = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeoutSecs() {
        
        timeoutSecs_ = 0;
        onChanged();
        return this;
      }

      private greptime.v1.meta.Common.ProcedureEventContext eventContext_;
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.ProcedureEventContext, greptime.v1.meta.Common.ProcedureEventContext.Builder, greptime.v1.meta.Common.ProcedureEventContextOrBuilder> eventContextBuilder_;
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       * @return Whether the eventContext field is set.
       */
      public boolean hasEventContext() {
        return eventContextBuilder_ != null || eventContext_ != null;
      }
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       * @return The eventContext.
       */
      public greptime.v1.meta.Common.ProcedureEventContext getEventContext() {
        if (eventContextBuilder_ == null) {
          return eventContext_ == null ? greptime.v1.meta.Common.ProcedureEventContext.getDefaultInstance() : eventContext_;
        } else {
          return eventContextBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       */
      public Builder setEventContext(greptime.v1.meta.Common.ProcedureEventContext value) {
        if (eventContextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventContext_ = value;
          onChanged();
        } else {
          eventContextBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       */
      public Builder setEventContext(
          greptime.v1.meta.Common.ProcedureEventContext.Builder builderForValue) {
        if (eventContextBuilder_ == null) {
          eventContext_ = builderForValue.build();
          onChanged();
        } else {
          eventContextBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       */
      public Builder mergeEventContext(greptime.v1.meta.Common.ProcedureEventContext value) {
        if (eventContextBuilder_ == null) {
          if (eventContext_ != null) {
            eventContext_ =
              greptime.v1.meta.Common.ProcedureEventContext.newBuilder(eventContext_).mergeFrom(value).buildPartial();
          } else {
            eventContext_ = value;
          }
          onChanged();
        } else {
          eventContextBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       */
      public Builder clearEventContext() {
        if (eventContextBuilder_ == null) {
          eventContext_ = null;
          onChanged();
        } else {
          eventContext_ = null;
          eventContextBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       */
      public greptime.v1.meta.Common.ProcedureEventContext.Builder getEventContextBuilder() {
        
        onChanged();
        return getEventContextFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       */
      public greptime.v1.meta.Common.ProcedureEventContextOrBuilder getEventContextOrBuilder() {
        if (eventContextBuilder_ != null) {
          return eventContextBuilder_.getMessageOrBuilder();
        } else {
          return eventContext_ == null ?
              greptime.v1.meta.Common.ProcedureEventContext.getDefaultInstance() : eventContext_;
        }
      }
      /**
       * <pre>
       * Stable event metadata recorded with the submitted procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureEventContext event_context = 67;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.ProcedureEventContext, greptime.v1.meta.Common.ProcedureEventContext.Builder, greptime.v1.meta.Common.ProcedureEventContextOrBuilder> 
          getEventContextFieldBuilder() {
        if (eventContextBuilder_ == null) {
          eventContextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              greptime.v1.meta.Common.ProcedureEventContext, greptime.v1.meta.Common.ProcedureEventContext.Builder, greptime.v1.meta.Common.ProcedureEventContextOrBuilder>(
                  getEventContext(),
                  getParentForChildren(),
                  isClean());
          eventContext_ = null;
        }
        return eventContextBuilder_;
      }

      private greptime.v1.meta.Common.ProcedureActor actor_;
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.ProcedureActor, greptime.v1.meta.Common.ProcedureActor.Builder, greptime.v1.meta.Common.ProcedureActorOrBuilder> actorBuilder_;
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       * @return Whether the actor field is set.
       */
      public boolean hasActor() {
        return actorBuilder_ != null || actor_ != null;
      }
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       * @return The actor.
       */
      public greptime.v1.meta.Common.ProcedureActor getActor() {
        if (actorBuilder_ == null) {
          return actor_ == null ? greptime.v1.meta.Common.ProcedureActor.getDefaultInstance() : actor_;
        } else {
          return actorBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       */
      public Builder setActor(greptime.v1.meta.Common.ProcedureActor value) {
        if (actorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          actor_ = value;
          onChanged();
        } else {
          actorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       */
      public Builder setActor(
          greptime.v1.meta.Common.ProcedureActor.Builder builderForValue) {
        if (actorBuilder_ == null) {
          actor_ = builderForValue.build();
          onChanged();
        } else {
          actorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       */
      public Builder mergeActor(greptime.v1.meta.Common.ProcedureActor value) {
        if (actorBuilder_ == null) {
          if (actor_ != null) {
            actor_ =
              greptime.v1.meta.Common.ProcedureActor.newBuilder(actor_).mergeFrom(value).buildPartial();
          } else {
            actor_ = value;
          }
          onChanged();
        } else {
          actorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       */
      public Builder clearActor() {
        if (actorBuilder_ == null) {
          actor_ = null;
          onChanged();
        } else {
          actor_ = null;
          actorBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       */
      public greptime.v1.meta.Common.ProcedureActor.Builder getActorBuilder() {
        
        onChanged();
        return getActorFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       */
      public greptime.v1.meta.Common.ProcedureActorOrBuilder getActorOrBuilder() {
        if (actorBuilder_ != null) {
          return actorBuilder_.getMessageOrBuilder();
        } else {
          return actor_ == null ?
              greptime.v1.meta.Common.ProcedureActor.getDefaultInstance() : actor_;
        }
      }
      /**
       * <pre>
       * Effective user that submitted the procedure.
       * </pre>
       *
       * <code>.greptime.v1.meta.ProcedureActor actor = 68;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.ProcedureActor, greptime.v1.meta.Common.ProcedureActor.Builder, greptime.v1.meta.Common.ProcedureActorOrBuilder> 
          getActorFieldBuilder() {
        if (actorBuilder_ == null) {
          actorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              greptime.v1.meta.Common.ProcedureActor, greptime.v1.meta.Common.ProcedureActor.Builder, greptime.v1.meta.Common.ProcedureActorOrBuilder>(
                  getActor(),
                  getParentForChildren(),
                  isClean());
          actor_ = null;
        }
        return actorBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:greptime.v1.meta.MigrateRegionRequest)
    }

    // @@protoc_insertion_point(class_scope:greptime.v1.meta.MigrateRegionRequest)
    private static final greptime.v1.meta.Region.MigrateRegionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new greptime.v1.meta.Region.MigrateRegionRequest();
    }

    public static greptime.v1.meta.Region.MigrateRegionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MigrateRegionRequest>
        PARSER = new com.google.protobuf.AbstractParser<MigrateRegionRequest>() {
      @java.lang.Override
      public MigrateRegionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MigrateRegionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MigrateRegionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MigrateRegionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public greptime.v1.meta.Region.MigrateRegionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MigrateRegionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:greptime.v1.meta.MigrateRegionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
     * @return The header.
     */
    greptime.v1.meta.Common.ResponseHeader getHeader();
    /**
     * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
     */
    greptime.v1.meta.Common.ResponseHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
     * @return Whether the pid field is set.
     */
    boolean hasPid();
    /**
     * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
     * @return The pid.
     */
    greptime.v1.meta.Common.ProcedureId getPid();
    /**
     * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
     */
    greptime.v1.meta.Common.ProcedureIdOrBuilder getPidOrBuilder();
  }
  /**
   * Protobuf type {@code greptime.v1.meta.MigrateRegionResponse}
   */
  public static final class MigrateRegionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:greptime.v1.meta.MigrateRegionResponse)
      MigrateRegionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MigrateRegionResponse.newBuilder() to construct.
    private MigrateRegionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MigrateRegionResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MigrateRegionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MigrateRegionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              greptime.v1.meta.Common.ResponseHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(greptime.v1.meta.Common.ResponseHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              greptime.v1.meta.Common.ProcedureId.Builder subBuilder = null;
              if (pid_ != null) {
                subBuilder = pid_.toBuilder();
              }
              pid_ = input.readMessage(greptime.v1.meta.Common.ProcedureId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pid_);
                pid_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              greptime.v1.meta.Region.MigrateRegionResponse.class, greptime.v1.meta.Region.MigrateRegionResponse.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private greptime.v1.meta.Common.ResponseHeader header_;
    /**
     * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public greptime.v1.meta.Common.ResponseHeader getHeader() {
      return header_ == null ? greptime.v1.meta.Common.ResponseHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
     */
    @java.lang.Override
    public greptime.v1.meta.Common.ResponseHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int PID_FIELD_NUMBER = 2;
    private greptime.v1.meta.Common.ProcedureId pid_;
    /**
     * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
     * @return Whether the pid field is set.
     */
    @java.lang.Override
    public boolean hasPid() {
      return pid_ != null;
    }
    /**
     * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
     * @return The pid.
     */
    @java.lang.Override
    public greptime.v1.meta.Common.ProcedureId getPid() {
      return pid_ == null ? greptime.v1.meta.Common.ProcedureId.getDefaultInstance() : pid_;
    }
    /**
     * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
     */
    @java.lang.Override
    public greptime.v1.meta.Common.ProcedureIdOrBuilder getPidOrBuilder() {
      return getPid();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (pid_ != null) {
        output.writeMessage(2, getPid());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (pid_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPid());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof greptime.v1.meta.Region.MigrateRegionResponse)) {
        return super.equals(obj);
      }
      greptime.v1.meta.Region.MigrateRegionResponse other = (greptime.v1.meta.Region.MigrateRegionResponse) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasPid() != other.hasPid()) return false;
      if (hasPid()) {
        if (!getPid()
            .equals(other.getPid())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasPid()) {
        hash = (37 * hash) + PID_FIELD_NUMBER;
        hash = (53 * hash) + getPid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static greptime.v1.meta.Region.MigrateRegionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(greptime.v1.meta.Region.MigrateRegionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code greptime.v1.meta.MigrateRegionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:greptime.v1.meta.MigrateRegionResponse)
        greptime.v1.meta.Region.MigrateRegionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                greptime.v1.meta.Region.MigrateRegionResponse.class, greptime.v1.meta.Region.MigrateRegionResponse.Builder.class);
      }

      // Construct using greptime.v1.meta.Region.MigrateRegionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (pidBuilder_ == null) {
          pid_ = null;
        } else {
          pid_ = null;
          pidBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return greptime.v1.meta.Region.internal_static_greptime_v1_meta_MigrateRegionResponse_descriptor;
      }

      @java.lang.Override
      public greptime.v1.meta.Region.MigrateRegionResponse getDefaultInstanceForType() {
        return greptime.v1.meta.Region.MigrateRegionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public greptime.v1.meta.Region.MigrateRegionResponse build() {
        greptime.v1.meta.Region.MigrateRegionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public greptime.v1.meta.Region.MigrateRegionResponse buildPartial() {
        greptime.v1.meta.Region.MigrateRegionResponse result = new greptime.v1.meta.Region.MigrateRegionResponse(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (pidBuilder_ == null) {
          result.pid_ = pid_;
        } else {
          result.pid_ = pidBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof greptime.v1.meta.Region.MigrateRegionResponse) {
          return mergeFrom((greptime.v1.meta.Region.MigrateRegionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(greptime.v1.meta.Region.MigrateRegionResponse other) {
        if (other == greptime.v1.meta.Region.MigrateRegionResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasPid()) {
          mergePid(other.getPid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        greptime.v1.meta.Region.MigrateRegionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (greptime.v1.meta.Region.MigrateRegionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private greptime.v1.meta.Common.ResponseHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.ResponseHeader, greptime.v1.meta.Common.ResponseHeader.Builder, greptime.v1.meta.Common.ResponseHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       * @return The header.
       */
      public greptime.v1.meta.Common.ResponseHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? greptime.v1.meta.Common.ResponseHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(greptime.v1.meta.Common.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       */
      public Builder setHeader(
          greptime.v1.meta.Common.ResponseHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       */
      public Builder mergeHeader(greptime.v1.meta.Common.ResponseHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              greptime.v1.meta.Common.ResponseHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       */
      public greptime.v1.meta.Common.ResponseHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       */
      public greptime.v1.meta.Common.ResponseHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              greptime.v1.meta.Common.ResponseHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.greptime.v1.meta.ResponseHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.ResponseHeader, greptime.v1.meta.Common.ResponseHeader.Builder, greptime.v1.meta.Common.ResponseHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              greptime.v1.meta.Common.ResponseHeader, greptime.v1.meta.Common.ResponseHeader.Builder, greptime.v1.meta.Common.ResponseHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private greptime.v1.meta.Common.ProcedureId pid_;
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.ProcedureId, greptime.v1.meta.Common.ProcedureId.Builder, greptime.v1.meta.Common.ProcedureIdOrBuilder> pidBuilder_;
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       * @return Whether the pid field is set.
       */
      public boolean hasPid() {
        return pidBuilder_ != null || pid_ != null;
      }
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       * @return The pid.
       */
      public greptime.v1.meta.Common.ProcedureId getPid() {
        if (pidBuilder_ == null) {
          return pid_ == null ? greptime.v1.meta.Common.ProcedureId.getDefaultInstance() : pid_;
        } else {
          return pidBuilder_.getMessage();
        }
      }
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       */
      public Builder setPid(greptime.v1.meta.Common.ProcedureId value) {
        if (pidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pid_ = value;
          onChanged();
        } else {
          pidBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       */
      public Builder setPid(
          greptime.v1.meta.Common.ProcedureId.Builder builderForValue) {
        if (pidBuilder_ == null) {
          pid_ = builderForValue.build();
          onChanged();
        } else {
          pidBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       */
      public Builder mergePid(greptime.v1.meta.Common.ProcedureId value) {
        if (pidBuilder_ == null) {
          if (pid_ != null) {
            pid_ =
              greptime.v1.meta.Common.ProcedureId.newBuilder(pid_).mergeFrom(value).buildPartial();
          } else {
            pid_ = value;
          }
          onChanged();
        } else {
          pidBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       */
      public Builder clearPid() {
        if (pidBuilder_ == null) {
          pid_ = null;
          onChanged();
        } else {
          pid_ = null;
          pidBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       */
      public greptime.v1.meta.Common.ProcedureId.Builder getPidBuilder() {
        
        onChanged();
        return getPidFieldBuilder().getBuilder();
      }
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       */
      public greptime.v1.meta.Common.ProcedureIdOrBuilder getPidOrBuilder() {
        if (pidBuilder_ != null) {
          return pidBuilder_.getMessageOrBuilder();
        } else {
          return pid_ == null ?
              greptime.v1.meta.Common.ProcedureId.getDefaultInstance() : pid_;
        }
      }
      /**
       * <code>.greptime.v1.meta.ProcedureId pid = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          greptime.v1.meta.Common.ProcedureId, greptime.v1.meta.Common.ProcedureId.Builder, greptime.v1.meta.Common.ProcedureIdOrBuilder> 
          getPidFieldBuilder() {
        if (pidBuilder_ == null) {
          pidBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              greptime.v1.meta.Common.ProcedureId, greptime.v1.meta.Common.ProcedureId.Builder, greptime.v1.meta.Common.ProcedureIdOrBuilder>(
                  getPid(),
                  getParentForChildren(),
                  isClean());
          pid_ = null;
        }
        return pidBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:greptime.v1.meta.MigrateRegionResponse)
    }

    // @@protoc_insertion_point(class_scope:greptime.v1.meta.MigrateRegionResponse)
    private static final greptime.v1.meta.Region.MigrateRegionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new greptime.v1.meta.Region.MigrateRegionResponse();
    }

    public static greptime.v1.meta.Region.MigrateRegionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MigrateRegionResponse>
        PARSER = new com.google.protobuf.AbstractParser<MigrateRegionResponse>() {
      @java.lang.Override
      public MigrateRegionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MigrateRegionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MigrateRegionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MigrateRegionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public greptime.v1.meta.Region.MigrateRegionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greptime_v1_meta_MigrateRegionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greptime_v1_meta_MigrateRegionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_greptime_v1_meta_MigrateRegionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_greptime_v1_meta_MigrateRegionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035greptime/v1/meta/region.proto\022\020greptim" +
      "e.v1.meta\032\035greptime/v1/meta/common.proto" +
      "\"\205\002\n\024MigrateRegionRequest\022/\n\006header\030\001 \001(" +
      "\0132\037.greptime.v1.meta.RequestHeader\022\021\n\tre" +
      "gion_id\030\003 \001(\004\022\021\n\tfrom_peer\030\004 \001(\004\022\017\n\007to_p" +
      "eer\030\005 \001(\004\022\024\n\014timeout_secs\030\006 \001(\r\022>\n\revent" +
      "_context\030C \001(\0132\'.greptime.v1.meta.Proced" +
      "ureEventContext\022/\n\005actor\030D \001(\0132 .greptim" +
      "e.v1.meta.ProcedureActor\"u\n\025MigrateRegio" +
      "nResponse\0220\n\006header\030\001 \001(\0132 .greptime.v1." +
      "meta.ResponseHeader\022*\n\003pid\030\002 \001(\0132\035.grept" +
      "ime.v1.meta.ProcedureIdB<Z:github.com/Gr" +
      "eptimeTeam/greptime-proto/go/greptime/v1" +
      "/metab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          greptime.v1.meta.Common.getDescriptor(),
        });
    internal_static_greptime_v1_meta_MigrateRegionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_greptime_v1_meta_MigrateRegionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greptime_v1_meta_MigrateRegionRequest_descriptor,
        new java.lang.String[] { "Header", "RegionId", "FromPeer", "ToPeer", "TimeoutSecs", "EventContext", "Actor", });
    internal_static_greptime_v1_meta_MigrateRegionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_greptime_v1_meta_MigrateRegionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_greptime_v1_meta_MigrateRegionResponse_descriptor,
        new java.lang.String[] { "Header", "Pid", });
    greptime.v1.meta.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
